apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: dealership-api:latest
        ports:
        - containerPort: 3030
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/dealership"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 3030
    targetPort: 3030
